[2023-01-06 09:14:02,968] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data.rm_task manual__2023-01-06T08:30:41.262614+00:00 [queued]>
[2023-01-06 09:14:02,987] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data.rm_task manual__2023-01-06T08:30:41.262614+00:00 [queued]>
[2023-01-06 09:14:02,987] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 09:14:02,987] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2023-01-06 09:14:02,988] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 09:14:03,007] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): rm_task> on 2023-01-06 08:30:41.262614+00:00
[2023-01-06 09:14:03,015] {standard_task_runner.py:52} INFO - Started process 5300 to run task
[2023-01-06 09:14:03,022] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data', 'rm_task', 'manual__2023-01-06T08:30:41.262614+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmprzu4wizj', '--error-file', '/tmp/tmp0x7eo7g4']
[2023-01-06 09:14:03,024] {standard_task_runner.py:77} INFO - Job 34: Subtask rm_task
[2023-01-06 09:14:03,128] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data.rm_task manual__2023-01-06T08:30:41.262614+00:00 [running]> on host 5d77b11d05f0
[2023-01-06 09:14:03,216] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data
AIRFLOW_CTX_TASK_ID=rm_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T08:30:41.262614+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-06T08:30:41.262614+00:00
[2023-01-06 09:14:03,218] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-01-06 09:14:03,219] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm/opt/***/fhv_tripdata_2021-01.parquet']
[2023-01-06 09:14:03,234] {subprocess.py:85} INFO - Output:
[2023-01-06 09:14:03,237] {subprocess.py:89} INFO - bash: rm/opt/***/fhv_tripdata_2021-01.parquet: No such file or directory
[2023-01-06 09:14:03,238] {subprocess.py:93} INFO - Command exited with return code 127
[2023-01-06 09:14:03,260] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-06 09:14:03,273] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=yellow_taxi_data, task_id=rm_task, execution_date=20230106T083041, start_date=20230106T091402, end_date=20230106T091403
[2023-01-06 09:14:03,294] {standard_task_runner.py:92} ERROR - Failed to execute job 34 for task rm_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-06 09:14:03,314] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-01-06 09:14:03,383] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
