[2023-01-06 07:44:10,396] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data.rm_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-01-06 07:44:10,421] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_data.rm_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-01-06 07:44:10,421] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 07:44:10,421] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2023-01-06 07:44:10,421] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 07:44:10,448] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): rm_task> on 2019-03-02 06:00:00+00:00
[2023-01-06 07:44:10,456] {standard_task_runner.py:52} INFO - Started process 1558 to run task
[2023-01-06 07:44:10,470] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_data', 'rm_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpvwshej5z', '--error-file', '/tmp/tmpjdx5tpdh']
[2023-01-06 07:44:10,472] {standard_task_runner.py:77} INFO - Job 18: Subtask rm_task
[2023-01-06 07:44:10,588] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_data.rm_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host 5d77b11d05f0
[2023-01-06 07:44:10,673] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-01-06 07:44:10,718] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_data
AIRFLOW_CTX_TASK_ID=rm_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2023-01-06 07:44:10,719] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-01-06 07:44:10,723] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm/opt/***/yellow_tripdata_2019-03.parquet']
[2023-01-06 07:44:10,744] {subprocess.py:85} INFO - Output:
[2023-01-06 07:44:10,749] {subprocess.py:89} INFO - bash: rm/opt/***/yellow_tripdata_2019-03.parquet: No such file or directory
[2023-01-06 07:44:10,751] {subprocess.py:93} INFO - Command exited with return code 127
[2023-01-06 07:44:10,782] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-06 07:44:10,800] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=yellow_taxi_data, task_id=rm_task, execution_date=20190302T060000, start_date=20230106T074410, end_date=20230106T074410
[2023-01-06 07:44:10,831] {standard_task_runner.py:92} ERROR - Failed to execute job 18 for task rm_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-01-06 07:44:10,848] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-01-06 07:44:10,926] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
